### ISSUE TITLE
how to adjust batch_size?

### ISSUE THREAD

**Issue by MinzChan** [ZeConloss/ZeCon#1]
return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.17 GiB already allocated; 0 bytes free; 5.26 GiB reserved in total by PyTorch) If reserved
 memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

my pc cpu is i7-10870H gpu 1660Ti

**Comment by ZeConloss** [comment]
It takes more than 11 GB of memory size. It seems that you'll need a memory size greater than 11 GB.

**Comment by ZeConloss** [comment]
Reducing the batch size may result in a degradation of the output quality. 
However, you can try different batch sizes with `--batch_size` from arguments.py.
